"""bugfix with wrong name of column registered_at

Revision ID: ce6fe4182b50
Revises: 3ecc50c42efe
Create Date: 2023-02-22 15:06:00.568114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce6fe4182b50'
down_revision = '3ecc50c42efe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registered_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('user', 'registrered_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registrered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'registered_at')
    # ### end Alembic commands ###
